# Generated by Django 5.2.5 on 2025-08-27 12:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_exercise_set_workout_exercise_workout"),
    ]

    operations = [
        migrations.AddField(
            model_name="workout",
            name="is_draft",
            field=models.BooleanField(default=False),
        ),
    ]
