# Generated by Django 5.2.5 on 2025-09-28 20:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_workout_is_draft"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Food",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "calories",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "carbs",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "protein",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "fiber",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "fat",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="food",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Foods",
                "verbose_name_plural": "Foods",
                "db_table": "food",
            },
        ),
    ]
