# Generated by Django 5.2.5 on 2025-10-03 23:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0004_food"),
    ]

    operations = [
        migrations.AddField(
            model_name="food",
            name="tag",
            field=models.CharField(
                blank=True, default="Snack", max_length=50, null=True
            ),
        ),
    ]
